version: 2
jobs:
  build:
    machine:
      ruby:
        version: 2.4.1
    steps:
      - checkout
      - run:
          name: Check for dead links
          command: |
              gem install awesome_bot
              awesome_bot `find . -name '*.md'` --allow-dupe --base-url "https://github.com/matmoore/bookmarks/blob/$CIRCLE_SHA1/"
